/**
 * Оболочка симулятора по макету maket1.
 *
 * Будущие алгоритмы и типы потока показаны отключёнными: они будут активированы
 * после реализации в core, чтобы UI не имитировал несуществующую функциональность.
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { createAlgorithm, createRoadGraphPlanner, Dispatcher, generateArrivals, mulberry32, runSimulation, type CarWash, type PeakWindow, type RoadGraph, type SimConfig, type SimSnapshot, type SimulationResult, type VehicleSource, type VehicleType } from '@loadbalancer/core';
import './App.css';

const WASHES: CarWash[] = [
  { id: 'wash_a', name: 'Мойка A', coordinates: [700, 3000], posts: 4, serviceTimeMin: { sedan: 8, truck: 25, heavy_truck: 38, bus: 40 }, supportedTypes: ['sedan', 'truck'], isActive: true, schedule: { openHour: 0, closeHour: 24 } },
  { id: 'wash_b', name: 'Мойка B', coordinates: [5200, 700], posts: 3, serviceTimeMin: { sedan: 10, truck: 30, heavy_truck: 45, bus: 40 }, supportedTypes: ['sedan', 'truck', 'heavy_truck', 'bus'], isActive: true, schedule: { openHour: 0, closeHour: 24 } },
  { id: 'wash_e', name: 'Мойка E', coordinates: [5200, 3800], posts: 5, serviceTimeMin: { sedan: 7, truck: 22, heavy_truck: 35, bus: 36 }, supportedTypes: ['sedan', 'truck', 'heavy_truck', 'bus'], isActive: true, schedule: { openHour: 0, closeHour: 24 } },
];
const shares: Record<VehicleType, number> = { sedan: .55, truck: .22, heavy_truck: .08, bus: .15 };
/** Источники отражают схему road.txt: въезд и два внутренних цеха. */
const SOURCES: VehicleSource[] = [
  { id: 'entrance', name: 'Въезд с основной дороги', kind: 'entrance', coordinates: [3000, 5700] },
  { id: 'shop_1', name: 'Цех №1', kind: 'workshop', coordinates: [3000, 300] },
  { id: 'shop_2', name: 'Цех №2', kind: 'workshop', coordinates: [2100, 2200] },
  { id: 'shop_3', name: 'Цех №3', kind: 'workshop', coordinates: [4000, 4700] },
];
const ROAD_GRAPH: RoadGraph = {
  nodes: [
    ...SOURCES.map(source => ({ id: source.id, coordinates: source.coordinates })),
    { id: 'center', coordinates: [3000, 3000] }, { id: 'upper', coordinates: [3000, 1100] },
    { id: 'right_turn', coordinates: [4000, 3000] }, { id: 'e_turn', coordinates: [4700, 3000] }, { id: 'shop_2_turn', coordinates: [2100, 3000] },
    { id: 'wash_a', coordinates: [700, 3000] }, { id: 'wash_b', coordinates: [5200, 700] }, { id: 'wash_e', coordinates: [5200, 3800] },
  ],
  edges: [
    { from: 'entrance', to: 'center' }, { from: 'shop_2', to: 'shop_2_turn' }, { from: 'shop_2_turn', to: 'center' },
    { from: 'center', to: 'wash_a' }, { from: 'center', to: 'right_turn' }, { from: 'right_turn', to: 'e_turn' }, { from: 'e_turn', to: 'wash_e' },
    { from: 'center', to: 'upper' }, { from: 'upper', to: 'shop_1' }, { from: 'upper', to: 'wash_b' },
    { from: 'right_turn', to: 'shop_3' },
  ],
};
const routePlanner = createRoadGraphPlanner(ROAD_GRAPH);
const algorithms = ['random', 'jsq', 'weighted_jsq'] as const;
type Algorithm = typeof algorithms[number];
const labels: Record<Algorithm, string> = { random: 'Random', jsq: 'JSQ — Shortest Queue', weighted_jsq: 'Weighted JSQ' };
const colors: Record<string, string> = { wash_a: '#2879df', wash_b: '#39a967', wash_e: '#e64d58' };
function formatTime(minutes: number) { const h = Math.floor(minutes / 60); const m = Math.floor(minutes % 60); return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:00`; }
function run(seed: number, algorithm: Algorithm, lambda: number, horizon: number, peaks: PeakWindow[], washes: CarWash[]) {
  const config: SimConfig = { seed, algorithm, distanceMetric: 'manhattan', avgSpeedKmh: 20, timeScale: 1 };
  const arrivals = generateArrivals({ lambdaBasePerMin: lambda, horizonMin: horizon, gridSizeMeters: 6000, typeShares: shares, sources: SOURCES, peakWindows: peaks }, mulberry32(seed));
  return runSimulation({ washes, config, arrivals, recordSnapshots: true, snapshotIntervalMin: 5, routePlanner }, (w, c) => new Dispatcher(w, c, createAlgorithm(c.algorithm), routePlanner));
}
function getSnapshot(result: SimulationResult, time: number) { return result.snapshots.reduce<SimSnapshot | undefined>((last, value) => value.time <= time ? value : last, undefined); }
/**
 * В snapshot пока нет значения Erlang C Wq. До расширения контракта
 * SimSnapshot UI показывает только наглядную оценку очереди; это не KPI.
 */
function visualWait(wash: CarWash, state?: SimSnapshot['washes'][number]) {
  return ((state?.queueLength ?? 0) / Math.max(wash.posts, 1)) * wash.serviceTimeMin.sedan;
}

export default function App() {
  const [seed, setSeed] = useState(42); const [lambda, setLambda] = useState(.5); const [horizon, setHorizon] = useState(1440);
  const [peaks, setPeaks] = useState<PeakWindow[]>([{ startHour: 12, endHour: 13, factor: 3 }, { startHour: 17, endHour: 18, factor: 3 }]);
  const [washes, setWashes] = useState<CarWash[]>(WASHES);
  const [editingWashId, setEditingWashId] = useState<string | null>(null);
  const [selectedVehicleId, setSelectedVehicleId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Algorithm>('jsq'); const [results, setResults] = useState<Record<Algorithm, SimulationResult> | null>(null); const [singleRun, setSingleRun] = useState<{ algorithm: Algorithm; result: SimulationResult } | null>(null);
  const [time, setTime] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(10);
  const [visibility, setVisibility] = useState({ roads: true, posts: true, queues: true, values: true });
  const active = results?.[selected] ?? (singleRun?.algorithm === selected ? singleRun.result : undefined); const maxTime = active?.snapshots.at(-1)?.time ?? 0;
  const snapshot = useMemo(() => active && getSnapshot(active, time), [active, time]);
  const activeDecision = useMemo(() => active ? [...active.decisions].reverse().find(item => item.time <= time) : undefined, [active, time]);
  const inspectedRequest = selectedVehicleId ? active?.requests.find(item => item.id === selectedVehicleId) : undefined;
  const inspectedDecision = inspectedRequest ? active?.decisions.find(item => item.requestId === inspectedRequest.id) : activeDecision;
  const focusRequest = inspectedRequest ?? (activeDecision ? active?.requests.find(item => item.id === activeDecision.requestId) : undefined);
  const start = () => { const next = {} as Record<Algorithm, SimulationResult>; algorithms.forEach(a => next[a] = run(seed, a, lambda, horizon, peaks, washes)); setSingleRun(null); setResults(next); setTime(0); setPlaying(true); };
  const startSelected = () => { setResults(null); setSingleRun({ algorithm: selected, result: run(seed, selected, lambda, horizon, peaks, washes) }); setSelectedVehicleId(null); setTime(0); setPlaying(true); };
  const editingWash = washes.find(wash => wash.id === editingWashId);
  const updateWash = (id: string, update: Partial<CarWash>) => setWashes(current => current.map(wash => wash.id === id ? { ...wash, ...update } : wash));
  const updatePeak = (index: number, update: Partial<PeakWindow>) => setPeaks(current => current.map((peak, i) => i === index ? { ...peak, ...update } : peak));
  const inspectVehicle = (id: string) => { setSelectedVehicleId(id); setPlaying(false); };
  const animation = useRef<number>();
  useEffect(() => { if (!playing || !active) return; let last = performance.now(); const loop = (now: number) => { setTime(old => { const next = Math.min(maxTime, old + (now - last) / 1000 * speed); if (next === maxTime) setPlaying(false); return next; }); last = now; animation.current = requestAnimationFrame(loop); }; animation.current = requestAnimationFrame(loop); return () => { if (animation.current) cancelAnimationFrame(animation.current); }; }, [active, maxTime, playing, speed]);
  const metrics = active?.metrics;
  return <div className="app">
    <header><h1>Симулятор распределения нагрузки между автомойками</h1><div className="header-controls">
      <label>Балансировщик <select value={selected} onChange={e => { setSelected(e.target.value as Algorithm); setTime(0); }}><option value="jsq">{labels.jsq}</option><option value="weighted_jsq">{labels.weighted_jsq}</option><option value="random">{labels.random}</option><option disabled>Power of Two Choices — скоро</option><option disabled>Round Robin — скоро</option></select></label>
      <button className="primary" onClick={start}>▶ Запустить все</button><button onClick={startSelected}>▶ Запустить выбранный</button><button disabled={!active} onClick={() => setPlaying(v => !v)}>{playing ? '❚❚ Пауза' : '▶ Продолжить'}</button><button onClick={() => { setTime(0); setPlaying(false); }}>↻ Сброс</button>
    </div></header>
    <main><aside className="sidebar"><Panel title="Настройки симуляции">
      <Field label="Длительность" value={formatTime(horizon)}><input type="number" min="30" max="1440" value={horizon} onChange={e => setHorizon(Number(e.target.value))}/></Field>
      <Field label="Seed сценария" value="одинаковый поток"><input type="number" value={seed} onChange={e => setSeed(Number(e.target.value))}/></Field>
      <Field label="Шаг воспроизведения" value={`${speed} мин/с`}><select value={speed} onChange={e => setSpeed(Number(e.target.value))}><option value="1">1 мин/с</option><option value="10">10 мин/с</option><option value="50">50 мин/с</option></select></Field>
      <Field label="Поток машин (λ)" value={`${(lambda * 60).toFixed(0)} машин/час`}><input className="range" type="range" min=".1" max="1.5" step=".1" value={lambda} onChange={e => setLambda(Number(e.target.value))}/></Field>
      <div className="peak-editor"><b>Пиковые периоды</b>{peaks.map((peak, index) => <label key={index}>Пик {index + 1}<input type="number" min="0" max="23" value={peak.startHour} onChange={e => updatePeak(index, { startHour: Number(e.target.value) })}/><span>—</span><input type="number" min="1" max="24" value={peak.endHour} onChange={e => updatePeak(index, { endHour: Number(e.target.value) })}/><small>×{peak.factor}</small></label>)}</div>
      <label className="select-field">Тип потока<select defaultValue="poisson"><option value="poisson">Пуассоновский</option><option disabled>Равномерный — скоро</option><option disabled>Пиковый — скоро</option><option disabled>Исторические данные — скоро</option></select></label>
      <label className="check"><input type="checkbox" checked readOnly/>Учитывать расстояние <span title="Отключение требует параметра в алгоритмах core.">ⓘ</span></label>
    </Panel><Panel title="Отображение">{(['roads', 'posts', 'queues', 'values'] as const).map(key => <label className="check" key={key}><input type="checkbox" checked={visibility[key]} onChange={e => setVisibility({ ...visibility, [key]: e.target.checked })}/>{{ roads:'Показывать дороги', posts:'Показывать посты', queues:'Показывать очереди', values:'Показывать значения' }[key]}</label>)}</Panel>
    {editingWash && <><Panel title={'Параметры: ' + editingWash.name}><WashEditor wash={editingWash} onChange={updateWash}/></Panel><Panel title={'Заявки: ' + editingWash.name}>{active ? <WashVehicleList wash={editingWash} result={active} time={time} onSelect={request => { setSelectedVehicleId(request.id); setTime(request.assignedAt); setPlaying(false); }}/> : <small>Запустите симуляцию, чтобы увидеть список машин.</small>}</Panel></>}<Panel title="Типы машин"><VehicleLegend/></Panel><Panel title="Метрики системы (итог)"><Metric text="Обслужено машин" value={metrics ? String(metrics.completed) : '—'}/><Metric text="Среднее время ожидания" value={metrics ? `${metrics.avgWaitMin.toFixed(1)} мин` : '—'}/><Metric text="Средняя длина очереди" value={metrics ? (Object.values(active?.washMetrics ?? {}).reduce((sum, wash) => sum + wash.avgQueueLength, 0) / washes.length).toFixed(1) : '—'}/><Metric text="Загрузка системы (ρ)" value={metrics ? `${(metrics.avgRho * 100).toFixed(0)}%` : '—'}/><Metric text="Поток машин (λ)" value={`${(lambda * 60).toFixed(1)}/час`}/></Panel></aside>
    <section className="center"><div className="map"><Map washes={washes} result={active} time={time} onVehicleClick={inspectVehicle} onWashClick={setEditingWashId} snapshot={snapshot} visibility={visibility} route={focusRequest?.route}/>{!active && <div className="empty">Выберите алгоритм и нажмите «Запуск»</div>}</div>{active && <Decision result={active} decision={inspectedDecision} inspected={Boolean(inspectedRequest)}/>} {results && <ComparisonTable results={results} selected={selected} onSelect={algorithm => { setSelected(algorithm); setSelectedVehicleId(null); setTime(0); }}/>}<input className="timeline" type="range" min="0" max={maxTime || 1} step=".1" value={time} disabled={!active} onChange={e => setTime(Number(e.target.value))}/><div className="time-label"><span>{formatTime(time)}</span><span>{formatTime(maxTime)}</span></div>{active && <Table washes={washes} result={active} snapshot={snapshot}/>}</section>
    <aside className="right"><Panel title="Загрузка автомоек (ρ)">{washes.map(w => <Bar key={w.id} label={w.name.at(-1)!} value={snapshot?.washes.find(s => s.washId === w.id)?.rho ?? 0} color={colors[w.id]}/>)}</Panel><Panel title="Среднее время ожидания (Wq), мин"><Chart result={active} field="wait"/><Legend/></Panel><Panel title="Очереди (кол-во машин)"><Chart result={active} field="queue"/><Legend/></Panel></aside></main></div>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }
function Field({ label, value, children }: { label: string; value: string; children: React.ReactNode }) { return <label className="field"><span>{label}<b>{value}</b></span>{children}</label>; }
function Metric({ text, value }: { text: string; value: string }) { return <div className="metric"><span>{text}</span><b>{value}</b></div>; }
function Bar({ label, value, color }: { label: string; value: number; color: string }) { return <div className="bar"><span>{label}</span><div><i style={{ width: `${Math.min(value, 1) * 100}%`, background: color }}/></div><b>{value.toFixed(2)}</b></div>; }
function Legend() { return <div className="legend">{WASHES.map(w => <span key={w.id}><i style={{ background: colors[w.id] }}/>{w.name.at(-1)}</span>)}</div>; }
function routePosition(points: { coordinates: [number, number] }[], progress: number): [number, number] { if (points.length < 2) return points[0]?.coordinates ?? [0, 0]; const lengths = points.slice(1).map((point, index) => Math.hypot(point.coordinates[0] - points[index].coordinates[0], point.coordinates[1] - points[index].coordinates[1])); const total = lengths.reduce((sum, length) => sum + length, 0); let remaining = Math.max(0, Math.min(1, progress)) * total; for (let index = 0; index < lengths.length; index += 1) { if (remaining <= lengths[index]) { const start = points[index].coordinates; const end = points[index + 1].coordinates; const part = lengths[index] ? remaining / lengths[index] : 0; return [start[0] + (end[0] - start[0]) * part, start[1] + (end[1] - start[1]) * part]; } remaining -= lengths[index]; } return points.at(-1)!.coordinates; }
function Map({ washes, result, time, onWashClick, onVehicleClick, snapshot, visibility, route }: { washes: CarWash[]; result?: SimulationResult; time: number; onWashClick: (id: string) => void; onVehicleClick: (id: string) => void; snapshot?: SimSnapshot; visibility: Record<'roads' | 'posts' | 'queues' | 'values', boolean>; route?: { points: { coordinates: [number, number] }[] } }) { const transit = result?.requests.filter(request => request.route && request.arrivedAt !== undefined && request.assignedAt <= time && time < request.arrivedAt) ?? []; return <div className="factory">{visibility.roads && <RoadNetwork/>}{route && <svg viewBox="0 0 6000 6000" preserveAspectRatio="none" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: 3, pointerEvents: 'none' }}><polyline points={route.points.map(point => point.coordinates.join(',')).join(' ')} fill="none" stroke="#ffd166" strokeWidth="42" strokeLinecap="round" strokeLinejoin="round" opacity=".85"/></svg>}{SOURCES.map(source => <div className="source" key={source.id} style={{ left: source.coordinates[0] / 60 + '%', top: source.coordinates[1] / 60 + '%', transform: 'translate(-50%, -50%)', zIndex: 5 }}><b>{source.kind === 'entrance' ? '↥' : '▰'} {source.name}</b><small>{source.kind === 'entrance' ? 'поток снаружи' : 'внутренний поток'}</small></div>)}{transit.map(request => { const position = routePosition(request.route!.points, (time - request.assignedAt) / Math.max(request.arrivedAt! - request.assignedAt, .001)); return <VehicleGlyph key={request.id} onClick={() => onVehicleClick(request.id)} type={request.vehicle.type} priority={request.vehicle.priority} style={{ position: 'absolute', zIndex: 7, left: position[0] / 60 + '%', top: position[1] / 60 + '%', transform: 'translate(-50%, -50%)' }}/>; })}{washes.map((wash, index) => <Wash key={wash.id} onVehicleClick={onVehicleClick} onClick={onWashClick} wash={wash} snapshot={snapshot} state={snapshot?.washes.find(s => s.washId === wash.id)} color={colors[wash.id]} pos={index} visibility={visibility}/>)}</div>; }
function RoadNetwork() { return <svg viewBox="0 0 6000 6000" preserveAspectRatio="none" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: 1 }}>{ROAD_GRAPH.edges.map(edge => { const from = ROAD_GRAPH.nodes.find(node => node.id === edge.from)!; const to = ROAD_GRAPH.nodes.find(node => node.id === edge.to)!; return <line key={edge.from + edge.to} x1={from.coordinates[0]} y1={from.coordinates[1]} x2={to.coordinates[0]} y2={to.coordinates[1]} stroke="#343b43" strokeWidth="150" strokeLinecap="round"/>; })}{ROAD_GRAPH.edges.map(edge => { const from = ROAD_GRAPH.nodes.find(node => node.id === edge.from)!; const to = ROAD_GRAPH.nodes.find(node => node.id === edge.to)!; return <line key={'mark' + edge.from + edge.to} x1={from.coordinates[0]} y1={from.coordinates[1]} x2={to.coordinates[0]} y2={to.coordinates[1]} stroke="#e8eef5" strokeWidth="10" strokeDasharray="44 38" opacity=".75"/>; })}<path d="M2900 3000H3100M3000 2900V3100" stroke="#f8fafc" strokeWidth="22" strokeLinecap="round"/></svg>; }
function Wash({ wash, snapshot, state, color, visibility, onClick, onVehicleClick }: { wash: CarWash; snapshot?: SimSnapshot; state?: SimSnapshot['washes'][number]; color: string; pos: number; visibility: Record<'roads' | 'posts' | 'queues' | 'values', boolean>; onClick: (id: string) => void; onVehicleClick: (id: string) => void }) { const rho = state?.rho ?? 0; const busy = snapshot?.vehicles.filter(vehicle => vehicle.targetWashId === wash.id && vehicle.phase === 'busy') ?? []; const queued = snapshot?.vehicles.filter(vehicle => vehicle.targetWashId === wash.id && vehicle.phase === 'queued') ?? []; return <article className="wash" onClick={() => onClick(wash.id)} title="Нажмите, чтобы изменить параметры мойки" style={{ '--wash': color, left: wash.coordinates[0] / 60 + '%', top: wash.coordinates[1] / 60 + '%', transform: 'translate(-50%, -50%)', zIndex: 6, cursor: 'pointer' } as React.CSSProperties}><header><b>▥ &nbsp;{wash.name}</b><span>Посты (c): {wash.posts}</span></header><div className="wash-body">{visibility.queues && <div className="queue"><b>Очередь ({state?.queueLength ?? 0})</b><div>{queued.slice(0, 6).map(vehicle => <VehicleGlyph key={vehicle.id} type={vehicle.type} priority={vehicle.priority} onClick={() => onVehicleClick(vehicle.id)} compact/>)}</div></div>}{visibility.posts && <div className="posts"><b>Посты</b><div>{Array.from({ length: wash.posts }, (_, i) => <i key={i} style={{ display: 'grid', placeItems: 'center', background: '#101e2e', border: '1px solid #607286' }}>{busy[i] && <VehicleGlyph type={busy[i].type} priority={busy[i].priority} onClick={() => onVehicleClick(busy[i].id)} compact/>}</i>)}</div></div>}{visibility.values && <div className="stats"><span>μ<b>{(60 / wash.serviceTimeMin.sedan).toFixed(1)}</b><small>маш/ч</small></span><span>λ<b>{(rho * wash.posts * 60 / wash.serviceTimeMin.sedan).toFixed(1)}</b><small>маш/ч</small></span><span>ρ<b className={rho > .9 ? 'danger' : ''}>{rho.toFixed(2)}</b></span><span title="Визуальная оценка, не Erlang C"><b>{visualWait(wash, state).toFixed(1)}</b><small>Wq*</small></span></div>}</div></article>; }
function VehicleGlyph({ type, priority, compact, style, onClick }: { type: VehicleType; priority: 'urgent' | 'normal' | 'scheduled'; compact?: boolean; style?: React.CSSProperties; onClick?: () => void }) { const size = compact ? { sedan: [22, 14], truck: [27, 16], heavy_truck: [31, 18], bus: [32, 18] } : { sedan: [21, 12], truck: [29, 14], heavy_truck: [35, 16], bus: [38, 16] }; const pair = size[type]; const palette: Record<VehicleType, string> = { sedan: '#3487ee', truck: '#f0a329', heavy_truck: '#8b5cf6', bus: '#39b56d' }; return <i onClick={event => { event.stopPropagation(); onClick?.(); }} title={{ sedan: 'Легковая', truck: 'Грузовая', heavy_truck: 'Тяжёлый грузовик', bus: 'Автобус' }[type] + (priority === 'urgent' ? ' · срочная' : '')} style={{ display: 'inline-block', flex: 'none', cursor: onClick ? 'pointer' : undefined, width: pair[0], height: pair[1], borderRadius: type === 'bus' ? 3 : 6, background: palette[type], border: priority === 'urgent' ? '3px solid #ff4555' : '1px solid #e8eef5', boxShadow: priority === 'urgent' ? '0 0 9px #ff4555' : '0 1px 3px #0007', ...style }}/>; }
function VehicleLegend() { return <div style={{ display: 'grid', gap: 8, fontSize: 12 }}>{([{ type: 'sedan', name: 'Легковая' }, { type: 'truck', name: 'Грузовая' }, { type: 'heavy_truck', name: 'Тяжёлый грузовик' }, { type: 'bus', name: 'Автобус' }] as { type: VehicleType; name: string }[]).map(item => <span key={item.type} style={{ display: 'flex', alignItems: 'center', gap: 8 }}><VehicleGlyph type={item.type} priority="normal"/>{item.name}</span>)}<span style={{ display: 'flex', alignItems: 'center', gap: 8 }}><VehicleGlyph type="sedan" priority="urgent"/>Срочный приоритет</span></div>; }
function WashEditor({ wash, onChange }: { wash: CarWash; onChange: (id: string, update: Partial<CarWash>) => void }) { const setTime = (type: VehicleType, value: number) => onChange(wash.id, { serviceTimeMin: { ...wash.serviceTimeMin, [type]: Math.max(1, value) } }); const toggleType = (type: VehicleType, checked: boolean) => onChange(wash.id, { supportedTypes: checked ? [...wash.supportedTypes, type] : wash.supportedTypes.filter(item => item !== type) }); return <div style={{ display: 'grid', gap: 7, fontSize: 12 }}><label>Название<input value={wash.name} onChange={e => onChange(wash.id, { name: e.target.value })}/></label><label>Посты<input type="number" min="1" max="12" value={wash.posts} onChange={e => onChange(wash.id, { posts: Math.max(1, Number(e.target.value)) })}/></label><label className="check"><input type="checkbox" checked={wash.isActive} onChange={e => onChange(wash.id, { isActive: e.target.checked })}/>Мойка активна</label><b>Время обслуживания, мин</b>{(['sedan', 'truck', 'heavy_truck', 'bus'] as VehicleType[]).map(type => <label key={type}>{({ sedan: 'Легковая', truck: 'Грузовая', heavy_truck: 'Тяжёлый грузовик', bus: 'Автобус' })[type]}<input type="number" min="1" value={wash.serviceTimeMin[type]} onChange={e => setTime(type, Number(e.target.value))}/><span className="check"><input type="checkbox" checked={wash.supportedTypes.includes(type)} onChange={e => toggleType(type, e.target.checked)}/>принимать</span></label>)}<small>Изменения применятся при следующем запуске всех алгоритмов.</small></div>; }
function WashVehicleList({ wash, result, time, onSelect }: { wash: CarWash; result: SimulationResult; time: number; onSelect: (request: SimulationResult['requests'][number]) => void }) { const vehicles = result.requests.filter(request => request.targetWash === wash.id); const names: Record<VehicleType, string> = { sedan: 'Легк.', truck: 'Груз.', heavy_truck: 'Тяж.', bus: 'Автобус' }; const status = (request: SimulationResult['requests'][number]) => { if (time < request.assignedAt) return 'ожидается'; const phase = getSnapshot(result, time)?.vehicles.find(vehicle => vehicle.id === request.id)?.phase; return ({ transit: 'в пути', queued: 'очередь', busy: 'пост', completed: 'готово' } as Record<string, string>)[phase ?? ''] ?? 'в обработке'; }; return <div style={{ maxHeight: 260, overflowY: 'auto' }}><small>Всего: {vehicles.length}. Нажмите строку, чтобы перейти к решению.</small><table style={{ fontSize: 11, marginTop: 6 }}><thead><tr><th>ID</th><th>Тип</th><th>Статус</th><th>Путь</th></tr></thead><tbody>{vehicles.map(request => <tr key={request.id} onClick={() => onSelect(request)} style={{ cursor: 'pointer', background: request.assignedAt === time ? '#1d4d3b88' : undefined }} title="Перейти к моменту решения балансировщика"><td>{request.id.replace('request-', '#')}</td><td>{names[request.vehicle.type]}</td><td>{status(request)}</td><td>{request.arrivedAt ? (request.arrivedAt - request.assignedAt).toFixed(1) + ' м' : '—'}</td></tr>)}</tbody></table></div>; }
function ComparisonTable({ results, selected, onSelect }: { results: Record<Algorithm, SimulationResult>; selected: Algorithm; onSelect: (algorithm: Algorithm) => void }) { const score = (m: SimulationResult['metrics']) => { const wait = Math.max(0, 1 - m.avgWaitMin / 15); const travel = Math.max(0, 1 - m.avgTravelMin / 25); const rho = Math.max(0, 1 - Math.abs(m.avgRho - .8) / .8); return 100 * (.32 * wait + .2 * travel + .2 * (1 - m.slaViolationRate) + .16 * m.jainFairness + .12 * rho); }; const scores = Object.fromEntries(algorithms.map(algorithm => [algorithm, score(results[algorithm].metrics)])) as Record<Algorithm, number>; const winner = algorithms.reduce((best, algorithm) => scores[algorithm] > scores[best] ? algorithm : best); return <section className="table-panel" style={{ marginTop: 8 }}><h2>Сравнение балансировщиков</h2><table><thead><tr><th>Алгоритм</th><th>avg Wq</th><th>Путь</th><th>SLA &gt;15</th><th>Jain</th><th>Score</th></tr></thead><tbody>{algorithms.map(algorithm => { const m = results[algorithm].metrics; return <tr key={algorithm} onClick={() => onSelect(algorithm)} title="Показать этот прогон" style={{ cursor: 'pointer', background: algorithm === selected ? '#3b82f655' : algorithm === winner ? '#1d4d3b66' : undefined }}><td>{labels[algorithm]}{algorithm === selected ? ' ✓' : ''}</td><td>{m.avgWaitMin.toFixed(2)} мин</td><td>{m.avgTravelMin.toFixed(2)} мин</td><td>{(m.slaViolationRate * 100).toFixed(1)}%</td><td>{m.jainFairness.toFixed(3)}</td><td><b>{scores[algorithm].toFixed(1)}</b></td></tr>; })}</tbody></table><small style={{ display: 'block', padding: '0 12px 10px', color: '#aebdcb' }}>Нажмите строку, чтобы показать этот прогон на карте и в сводной таблице. Score 0–100: ожидание 32%, путь 20%, SLA 20%, равномерность 16%, близость к ρ=80% 12%.</small></section>; }
function Table({ washes, result, snapshot }: { washes: CarWash[]; result: SimulationResult; snapshot?: SimSnapshot }) { return <section className="table-panel"><h2>Сводная таблица по автомойкам</h2><table><thead><tr><th>Мойка</th><th>Посты (c)</th><th>μ (маш/ч)</th><th>λ (маш/ч)</th><th>ρ</th><th>Wq* (мин)</th><th>Очередь</th><th>Обслужено</th></tr></thead><tbody>{washes.map(w => { const s = snapshot?.washes.find(x => x.washId === w.id); return <tr key={w.id}><td><i className="badge" style={{ background: colors[w.id] }}>{w.name.at(-1)}</i></td><td>{w.posts}</td><td>{(60 / w.serviceTimeMin.sedan).toFixed(1)}</td><td>{((s?.rho ?? 0) * w.posts * 60 / w.serviceTimeMin.sedan).toFixed(1)}</td><td>{(s?.rho ?? 0).toFixed(2)}</td><td title="Визуальная оценка, не Erlang C">{visualWait(w, s).toFixed(1)}</td><td>{s?.queueLength ?? 0}</td><td>{result.washMetrics[w.id]?.completed ?? 0}</td></tr>; })}</tbody></table></section>; }
function Decision({ result, decision, inspected }: { result: SimulationResult; decision: SimulationResult['decisions'][number] | undefined; inspected: boolean }) {
  if (!decision) return <div className="decision">Ожидание первой заявки…</div>;
  const request = result.requests.find(item => item.id === decision.requestId);
  const source = request?.vehicle.source?.name ?? 'неизвестный источник';
  return <div className="decision"><div><b>{inspected ? 'Выбранный автомобиль: ' : ''}{source}</b><span> → {inspected ? 'показано принятое для него решение' : 'Balancer рассмотрел доступные мойки'}; жёлтая линия показывает маршрут.</span></div><div style={{ display: 'flex', gap: 7, width: '100%' }}>{decision.candidates.map(candidate => { const wash = WASHES.find(item => item.id === candidate.washId); const chosen = candidate.washId === decision.chosenWash; return <div key={candidate.washId} style={{ flex: 1, padding: 8, border: chosen ? '2px solid #ffd166' : '1px solid #33475d', borderRadius: 5, background: chosen ? '#4a3c1633' : '#101f31' }}><b style={{ color: colors[candidate.washId] }}>{wash?.name ?? candidate.washId}{chosen ? ' ✓' : ''}</b><small style={{ display: 'block', marginTop: 4 }}>Путь {candidate.travelTimeMin.toFixed(1)} мин · Wq {candidate.expectedWaitMin.toFixed(1)} мин · ρ {candidate.rho.toFixed(2)}</small><strong style={{ display: 'block', marginTop: 4 }}>Score {candidate.score.toFixed(2)}</strong></div>; })}</div></div>;
}
function Chart({ result, field }: { result?: SimulationResult; field: 'wait' | 'queue' }) { if (!result) return <div className="chart empty-chart">Данные появятся после запуска</div>; const points = result.snapshots.filter((_, i) => i % Math.max(1, Math.floor(result.snapshots.length / 30)) === 0); const max = Math.max(1, ...points.flatMap(s => s.washes.map(w => field === 'wait' ? visualWait(WASHES.find(x => x.id === w.washId)!, w) : w.queueLength))); return <svg className="chart" viewBox="0 0 260 110" preserveAspectRatio="none">{WASHES.map(w => <polyline key={w.id} fill="none" stroke={colors[w.id]} strokeWidth="2" points={points.map((s,i) => { const v=s.washes.find(x=>x.washId===w.id); const n=field==='wait'?visualWait(w, v):v?.queueLength??0; return `${i/Math.max(points.length-1,1)*260},${105-n/max*90}`; }).join(' ')}/>)}</svg>; }
